import { ReactQueryProvider } from "@/providers/reactQueryProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { DM_Sans } from "next/font/google";
import "./globals.scss";

import { ThemeProvider } from "@/providers/antdThemeProvider";
import SessionProvider from "@/providers/SessionProvider";
const dm_sans = DM_Sans({ subsets: ["latin"], variable: "--font-dm-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={dm_sans.variable}>
        <ThemeProvider>
          <SessionProvider session={session}>
            <AntdRegistry>
              <ReactQueryProvider>{children}</ReactQueryProvider>
            </AntdRegistry>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
