export enum PermissionsEnum {
  HOME_VIEW = "HOME_VIEW",
  PLAYGROUND_VIEW = "PLAYGROUND_VIEW",
  AGENTS_VIEW = "AGENTS_VIEW",
  WORKFLOWS_VIEW = "WORKFLOWS_VIEW",
  WORKSPACE_VIEW = "WORKSPACE_VIEW",
  MODELS_VIEW = "MODELS_VIEW",
  DATASET_VIEW = "DATASET_VIEW",
  KNOWLEDGEBASE_VIEW = "KNOWLEDGEBASE_VIEW",
  INTEGRATION_VIEW = "INTEGRATION_VIEW",
  SETTINGS_VIEW = "SETTINGS_VIEW",
  BILLING_VIEW = "BILLING_VIEW",
}

export const PERMISSION: { [key in PermissionsEnum]: PermissionsEnum } = {
  HOME_VIEW: PermissionsEnum.HOME_VIEW,
  PLAYGROUND_VIEW: PermissionsEnum.PLAYGROUND_VIEW,
  AGENTS_VIEW: PermissionsEnum.AGENTS_VIEW,
  WORKFLOWS_VIEW: PermissionsEnum.WORKFLOWS_VIEW,
  WORKSPACE_VIEW: PermissionsEnum.WORKSPACE_VIEW,
  MODELS_VIEW: PermissionsEnum.MODELS_VIEW,
  DATASET_VIEW: PermissionsEnum.DATASET_VIEW,
  KNOWLEDGEBASE_VIEW: PermissionsEnum.KNOWLEDGEBASE_VIEW,
  INTEGRATION_VIEW: PermissionsEnum.INTEGRATION_VIEW,
  SETTINGS_VIEW: PermissionsEnum.SETTINGS_VIEW,
  BILLING_VIEW: PermissionsEnum.BILLING_VIEW,
};
