export enum BillingTabType {
  "OVERVIEW" = "OVERVIEW",
  "BILLING_HISTORY" = "BILLING_HISTORY",
  "PAYMENT_METHODS" = "PAYMENT_METHODS",
  "PRICING_PLANS" = "PRICING_PLANS",
}

export const BillingTab = {
  OVERVIEW: BillingTabType.OVERVIEW,
  BILLING_HISTORY: BillingTabType.BILLING_HISTORY,
  PAYMENT_METHODS: BillingTabType.PAYMENT_METHODS,
  PRICING_PLANS: BillingTabType.PRICING_PLANS,
};
